[book]
title = "coderWu"
authors = ["coderWu"]
language = "en"
multilingual = true
src = "./"

[preprocessor.toc]
command = "mdbook-toc"
render = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/coder-wu/blog"
no-section-label = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true   # whether or not to enable section folding
level = 0       # the depth to start folding

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
