baseURL = "https://blog.coderwu.com/"
languageCode = "en-us"
title = "coderWu"
theme = "yinyang"
DefaultContentLanguage = "cn"
keywords = [ "Blog", "coderWu"]
publishDir = "docs"


[author]
  name = "coderWu"
  homepage = "https://blog.coderwu.com/"
  mail = "coderwumail@gmail.com"

[languages]
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1
  [languages.en]
    contentDir = "content/cn"
    languageName = "English"
    weight = 2

[params]
extraHead = '<script type="text/javascript" src="https://s22.cnzz.com/z_stat.php?id=1273172286&web_id=1273172286"></script>'

[[params.socials]]
name = "Github"
link = "https://github.com/coder-wu/"
