baseURL: "https://blog.coderwu.com/"
title: Wu
theme: [PaperMod]

paginate: 10
defaultContentLanguage: zh

enableRobotsTXT: true
enableEmoji: true

languages:
  zh:
    languageCode: zh-CN
    languageName: 中文
    weight: 1
    menu:
      main:
        - name: 关于
          url: ../about
          weight: 1
        - name: 标签
          url: tags
          weight: 2
        - name: RSS
          url: zh/index.xml
          weight: 3

  en:
    languageCode: en-US
    languageName: English
    weight: 2
    menu:
      main:
        - name: About
          url: ../about
          weight: 1
        - name: Tags
          url: tags
          weight: 2
        - name: RSS
          url: en/index.xml
          weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  author: wu

  defaultTheme: auto
  disableSpecial1stPost: true

  hideSummary: true
  ShowReadingTime: false

  ShowShareButtons: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false

  assets:
    disableHLJS: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false